# Generated by Django 5.1.7 on 2025-04-07 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='role',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('user', 'Utilisateur standard'), ('agent', 'Agent administratif'), ('supervisor', 'Superviseur'), ('admin', 'Administrateur système')], default='user', max_length=20, verbose_name='Rôle'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='utilisateur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire'),
            preserve_default=False,
        ),
    ]
