# Generated by Django 5.1.7 on 2025-04-09 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_agent_role_utilisateur_role_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
