# Generated by Django 5.1.7 on 2025-04-09 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enregistrement',
            name='sexe',
            field=models.CharField(blank=True, choices=[('masculin', 'Masculin'), ('feminin', 'Feminin')], max_length=50, null=True),
        ),
    ]
